message = input("Tell me something ,and I will repeat it back to you:")
print(message)
name = input("Please enter your name: ")
print("Hello," + name + "!")
age=input("how old are you?")
print(age)
age=int(age)