cars = ['bmw', 'audi', 'toyota', 'subaru']
cars.sort()
print(cars)
cars.sort(reverse=True)
print(cars)
print(sorted(cars))
print(cars)
print(sorted(cars,reverse=True))
cars.reverse()
print(cars)
print(len(cars))